version: "2"

linters:
  default: none
  enable:
    - domainctor
  settings:
    custom:
      domainctor:
        path: ./plugin/domainctor.so
        description: Require NewXxx constructors for domain types and Execute signature for usecases.
        original-url: local
